# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epsiode_id', models.CharField(max_length=128, unique=True)),
                ('episode_title', models.CharField(max_length=256)),
                ('episode_num', models.IntegerField(default=1)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('runtime', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=128, unique=True)),
                ('season_num', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='tvseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.CharField(max_length=128, unique=True)),
                ('show_name', models.CharField(max_length=512)),
                ('year', models.IntegerField(default=2000)),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('poster', models.ImageField(upload_to='')),
                ('synopsis', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.tvseries'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='show_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.tvseries'),
        ),
    ]
