# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0002_auto_20180227_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv_show',
            options={'verbose_name': 'TV Show', 'verbose_name_plural': 'TV Shows'},
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tv_show',
            name='show_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
