# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0003_auto_20180228_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='synopsis',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='show_name',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='synopsis',
            field=models.TextField(max_length=10000),
        ),
    ]
