# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0004_auto_20180228_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='epsiode_id',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season_id',
        ),
        migrations.RemoveField(
            model_name='tv_show',
            name='id',
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='show_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
