# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0005_auto_20180301_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='season_id',
            new_name='season_num',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='show_id',
            new_name='show_name',
        ),
        migrations.AddField(
            model_name='episode',
            name='epsiode_id',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='season_id',
            field=models.CharField(default='', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='show_id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='show_name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='show_slug',
            field=models.SlugField(),
        ),
    ]
