# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 22:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0006_auto_20180301_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='airdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
