# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0007_episode_airdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('genre_name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tv_show',
            name='genres',
            field=models.ManyToManyField(to='tvtrail.genre'),
        ),
    ]
