# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tvtrail', '0008_auto_20180302_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_episode_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('watched', models.BooleanField(default=False)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.episode')),
            ],
        ),
        migrations.CreateModel(
            name='user_show_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='poster',
            field=models.ImageField(blank=True, upload_to='series_posters'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(to='tvtrail.tv_show'),
        ),
        migrations.AddField(
            model_name='user_show_relation',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.tv_show'),
        ),
        migrations.AddField(
            model_name='user_show_relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.UserProfile'),
        ),
        migrations.AddField(
            model_name='user_episode_relation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.UserProfile'),
        ),
    ]
