# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0010_auto_20180309_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_episode_relation',
            name='rating',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
