# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0011_auto_20180315_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_show',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
