# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0012_tv_show_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='tvtrail.tv_show'),
        ),
    ]
