# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0013_auto_20180319_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_show',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='episode',
            name='season_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tv_show',
            name='show_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, unique=True),
        ),
    ]
