# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0014_auto_20180320_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='epsiode_id',
            new_name='episode_id',
        ),
    ]
