# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0016_auto_20180321_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='avg_rating',
        ),
    ]
