# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0017_remove_episode_avg_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='buddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buddies', models.ManyToManyField(to='tvtrail.UserProfile')),
                ('current_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='tvtrail.UserProfile')),
            ],
        ),
    ]
