# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0018_buddy'),
    ]

    operations = [
        migrations.CreateModel(
            name='episode_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvtrail.UserProfile')),
                ('episode_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tvtrail.episode')),
            ],
        ),
    ]
