# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 14:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvtrail', '0019_episode_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddy',
            options={'verbose_name': 'Buddy', 'verbose_name_plural': 'Buddies'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
